<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJM0Tikv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJM0Tikv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJM0Tikv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJM0Tikv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJM0Tikv\App_KernelDevDebugContainer([
    'container.build_hash' => 'JM0Tikv',
    'container.build_id' => 'fb1ad41c',
    'container.build_time' => 1600073748,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJM0Tikv');
