<?php

namespace ContainerJM0Tikv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSprintApiControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SprintApiController' shared autowired service.
     *
     * @return \App\Controller\SprintApiController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/SprintApiController.php';

        $container->services['App\\Controller\\SprintApiController'] = $instance = new \App\Controller\SprintApiController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\SprintApiController', $container));

        return $instance;
    }
}
